### ISSUE TITLE
Synthetic Text Workflow / de-identification process

### ISSUE THREAD

**Issue by Jake-Gillberg** [OHNLP/N3C-NLP-Documentation#5]
Regarding the draft de-identification process shown on the [wiki](https://github.com/OHNLP/N3C-NLP-Documentation/wiki/Deidentification-Process):

Is there a reason the OHNLP concept extraction is being run on the N3C side? It seems like allowing this process to be run locally and have the results sent to N3C would be safer regarding the potential leakage of PHI and reduce the burden of manual review.

![process diagram](https://raw.githubusercontent.com/OHNLP/N3C-NLP-Documentation/master/n3c-deid-workflow1.png)

**Comment by ymnliu** [comment]
Hi @Jake-Gillberg, thanks for the suggestion. The purpose of this deid workflow is to compose a corpus that is PHI-free meanwhile good for developing IE algorithms. The deliverable will be a language resource maintained by the N3C NLP subgroup. Please note this is a different workflow from contributing the extracted clinical concepts from the texts (via running [OHNLP Backbone](https://github.com/OHNLP/Backbone)) to N3C Enclave. 

For contributing data to N3C Enclave, we do not currently plan to send any text data. All the fields with PHI risks will be truncated before submitting. Please check on our newly released instruction at https://github.com/OHNLP/N3C-NLP-Documentation/wiki/Contributing-data-to-N3C-Enclave. It leverages the baseline algorithm we developed and is safe, PHI-free and do not need manual review. 

With that being said, I have updated the homepage of this wiki to list out the goals: https://github.com/OHNLP/N3C-NLP-Documentation/wiki#goals. Hope it clarifies things a bit. Let me know if you have any questions.

**Comment by Jake-Gillberg** [comment]
Great, thanks for the explanation!
